name: 'PR validation'

on:
  pull_request:
    branches: [ next, latest, '!dependabot' ]

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.1.2
          run_install: true

      - name: Check for code quality issues
        run: pnpm lint-ci

      - name: Run tests
        run: pnpm test

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: packages/react
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: storybook:build
          exitOnceUploaded: true
